Read parquet file by path&Adapt INT96 etc. DataType&Support enable kerberos authentication
hugegraph/hugegraph-loader pull request #174
Opened 2020-11-11 08:02 UTC by tmljob

1、Read parquet file by path
2、Adapt INT96 etc. DataType
3、Support enable kerberos authentication

2020-11-11 08:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hugegraph/hugegraph-loader?pullRequest=174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hugegraph/hugegraph-loader?pullRequest=174) before we can accept your contribution.<br/><hr/>**tmljob@163.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hugegraph/hugegraph-loader?pullRequest=174) it.</sub>

2020-11-11 08:38 UTC, Linary commented
@tmljob 请拆分成两个commit，一个处理parquet相关的问题，一个支持kerberos。
ps：我微信号 liningrui，可以加个微信交流一下。

2020-11-11 08:43 UTC, Linary requested changes

2020-11-11 08:43 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +	private static final Logger LOG = Log.logger(ParquetFileLineFetcher.class);
注意不要用tab替换空格，代码的缩进请保持与原有风格一致

2020-11-12 03:58 UTC, Linary requested changes

2020-11-12 03:58 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +    private static final Logger LOG = Log.logger(ParquetFileLineFetcher.class);
请使用 \n 作为换行符，不要使用\r\n

2020-11-12 03:58 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +    	Path path = ((HDFSFile)readable).path();
第 111 行注意缩进

2020-11-12 03:58 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +    	Path path = ((HDFSFile)readable).path();
((HDFSFile)readable).path(); -> ((HDFSFile) readable).path();

2020-11-12 03:58 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            values[fieldIndex] = convertObject(group,fieldIndex);
`convertObject(group,fieldIndex);` -> `this.convertObject(group, fieldIndex);`

2020-11-12 08:47 UTC, Linary requested changes

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            values[fieldIndex] = this.convertObject(group,fieldIndex);
group和fieldIndex中间加空格

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +        Type filedType = group.getType().getType(fieldIndex);
filedType -> fieldType

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +        if (filedType.isPrimitive()) {
把
``` 
if (!filedType.isPrimitive()) {
    LOG.warn('xxx');
    return null;
}
```
放到前面

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            case INT32:
case INT32:
case INT64:
case INT96:

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            LOG.warn("unSupport rich object converter!objectType:{}",
Unsupported rich object type {},

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +        Path path = ((HDFSFile) readable).path();;
这个是必须要改的吗？

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSFileReader.java
> +    public static class HDFSFile implements Readable {
如果openReader不用改，这里也改回去

2020-11-12 08:47 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
> +                .with(JulianFields.JULIAN_DAY, julianDay).atTime(LocalTime.NOON)
对齐整理一下

2020-11-13 05:20 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +        Path path = ((HDFSFile) readable).path();;
是的，如果不这样改，映射文件path里面如果配置的是路径，就会报错了。
path":"/impala/storage/originald/ysk_sjlcs_xieyitest_1/"

2020-11-13 05:20 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSFileReader.java
> +    public static class HDFSFile implements Readable {
同上

2020-11-13 05:26 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
> +                .with(JulianFields.JULIAN_DAY, julianDay).atTime(LocalTime.NOON)
这个是按照行不超过80个字符的要求，自动format对齐的

2020-11-17 06:19 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +        Path path = ((HDFSFile) readable).path();;
好的

2020-11-17 06:19 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSFileReader.java
> +    public static class HDFSFile implements Readable {
那把LocalFile也设置为public的吧，对称

2020-11-17 06:25 UTC, Linary requested changes

2020-11-17 06:25 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
> +                .with(JulianFields.JULIAN_DAY, julianDay).atTime(LocalTime.NOON)
像这样对齐
```
LocalDateTime timestamp = LocalDate.MIN.with(JulianFields.JULIAN_DAY, 
                                             julianDay)
                                       .atTime(LocalTime.NOON)
                                       .plusNanos(nanos);
```

2020-11-17 06:25 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            object = DataTypeUtil
对齐改为
```
object = DataTypeUtil.dateFromInt96(
         group.getInt96(fieldType.getName(), 0));
```

2020-11-17 06:25 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
> +    public static Date dateFromInt96(Binary value) {
这个方法是否是参考出处，如果有的话，在方法上添加注释引用一下

2020-11-17 06:49 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +        Path path = ((HDFSFile) readable).path();;
去除多余的分号

2020-11-17 06:49 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            object = group.getValueToString(fieldIndex, 0);
可以统一加上break

2020-11-17 06:49 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +        case INT32:
缩进增加4格

2020-11-17 06:49 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +    private Object convertObject(Group group, int fieldIndex) {
是否可定义为static方法，不依赖this的话优先static

2020-11-17 06:49 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            LOG.warn("UnSupported rich object type {}", fieldType);
UnSupported => Unsupported
建议改为抛异常

2020-11-17 06:49 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            return null;
类似上面

2020-11-17 09:25 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            LOG.warn("UnSupported rich object type {}", fieldType);
抛异常不太好吧，程序中断执行了，还是返回空，打日志好些

2020-11-17 09:26 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            return null;
这里抛异常不太合适，是正常读取没有值的情况

2020-11-17 09:41 UTC, Linary requested changes

2020-11-17 09:41 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +            LOG.warn("Unsupported rich object type {}", fieldType);
还是抛异常比较好，这种是loader无法处理的情况，如果只是打了警告，用户可能会没注意到日志的警告，还以为这个字段也是成功了。

2020-11-17 09:41 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +            return null;
这里如果也会导致上面类似的情况，也需要抛异常

2020-11-17 09:41 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +
删除这个空行

2020-11-17 09:42 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            return null;
是这个字段为空或者null的意思吗？

2020-11-17 11:41 UTC, javeme requested changes

2020-11-17 11:41 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
> +    // reference:https://stackoverflow.com/questions/53690299/int96value-to-date-string
请使用java doc格式："/**"

2020-11-17 11:41 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +                        group.getInt96(fieldType.getName(), 0));
对齐DataTypeUtil

2020-11-17 11:41 UTC, javeme commented on src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
> +    public static Date dateFromInt96(Binary value) {
prefer to move to DateUtil class

2020-11-17 14:50 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            LOG.warn("UnSupported rich object type {}", fieldType);
已改为抛异常

2020-11-17 14:51 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
> +            return null;
是的

2020-11-17 14:51 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +            LOG.warn("Unsupported rich object type {}", fieldType);
好的，已修改

2020-11-17 14:54 UTC, tmljob commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +            return null;
正常没值，添加注释

2020-11-18 03:06 UTC, Linary approved these changes

2020-11-18 03:32 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +        //field is no value
// Field is no value

note the space between "//" and "Field"

2020-11-18 03:32 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +     */
```
// Reference:https://stackoverflow.com/questions/53690299/int96value-to-date-string
```
or 
```
/*
 * Reference:https://stackoverflow.com/questions/53690299/int96value-to-date-string
 */
```

2020-11-18 06:50 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java
> +     */
使用下面的方式

2020-11-18 08:04 UTC, Linary approved these changes

2020-11-18 08:42 UTC, zhoney approved these changes

2020-11-18 11:41 UTC, merged