Fix date unequal since client and server has not same time zone
hugegraph/hugegraph-loader pull request #192
Opened 2020-12-14 09:48 UTC by Linary

2020-12-15 08:17 UTC, javeme commented on src/test/java/com/baidu/hugegraph/loader/test/functional/LoadTest.java
> +    public static void assertDateEquals(List<String> expectDates,
are there multi expected date

2020-12-15 09:06 UTC, Linary commented on src/test/java/com/baidu/hugegraph/loader/test/functional/LoadTest.java
> +    public static void assertDateEquals(List<String> expectDates,
there exist, cardinality list and datatype date

2020-12-15 09:47 UTC, javeme requested changes

2020-12-15 09:47 UTC, javeme commented on src/test/java/com/baidu/hugegraph/loader/test/functional/LoadTest.java
> +                        "The size of expect and actual dates must be equal");
call Assert.assertEquals with error message param

2020-12-16 07:15 UTC, javeme approved these changes

2020-12-16 08:47 UTC, merged