fix #209
hugegraph/hugegraph-loader pull request #211
Opened 2021-05-12 11:03 UTC by DoubleBabylol

fix [#209](https://github.com/hugegraph/hugegraph-loader/issues/209)

2021-05-13 02:37 UTC, Linary requested changes

2021-05-13 02:37 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +        this.vertexIdsIndex = this.extractVertexIdsIndex(names);
每次build都重新提取下标开销太大。

![image](https://user-images.githubusercontent.com/9151831/118069449-cede9900-b3d6-11eb-8692-758f832b3649.png)

图中这个提交将属性的获取从map变成了数组下标访问的方式，你碰到的问题应该是由这个提交导致的。

请切到这个提交的前面一个提交，验证一下是否存在你的那个问题。如果不存在了，我觉得还是得改回用map访问的方式。

2021-05-13 07:00 UTC, DoubleBabylol commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +        this.vertexIdsIndex = this.extractVertexIdsIndex(names);
改回map的话 ，又回到了每行json创建map的情况。
如果对names进行判断，names代表json数据的key值，他没有变化就说明这行数据的索引位置和数值都没变，那么就只有在json的key变化的时候重新计算就可以了

2021-05-17 10:02 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +        this.vertexIdsIndex = this.extractVertexIdsIndex(names);
文件是Json的时候，现有代码是一定会生成一次map的，性能无影响的；受影响的是文件是CSV或TEXT格式的时候。
所以现在的方案就是两个：
1. 所有文件格式都先生成map，无需提取数组索引，这样CSV、TEXT有性能损耗，JSON无影响；
2. CSV、TEXT直接生成数组，JSON先生成map再转成数组，然后CSV、TEXT无性能损耗，JSON需要对比和重新提取，有损耗。

综合考虑，建议采用方案2，可做这样修改：

1. 文件是CSV和TEXT的时候，names其实每次都是header引用的那个对象，所以不会有变化，不用重新提取索引；每次都比较（或者用==比较的方式）；
2. 文件是JSON格式时，先对比，如果有改变就重新提取。

代码大概是：

```
private String[] lastNames;

...

public List<Edge> build(String[] names, Object[] values) {
        if (this.vertexIdsIndex == null || 
            (this.lastNames != names && !Arrays.equals(this.lastNames, names))) {
            this.vertexIdsIndex = this.extractVertexIdsIndex(names);
        }
        this.lastNames = names;
        ...
}
```

2021-05-18 02:55 UTC, Linary requested changes

2021-05-18 02:55 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +        this.vertexIdsIndex = this.extractVertexIdsIndex(names);
提交前先rebase一下master分支

2021-05-20 11:32 UTC, imbajin commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +import java.util.*;
keep original, use this[ config file](https://github.com/hugegraph/hugegraph/blob/master/hugegraph-style.xml)  with IDEA

2021-05-20 11:36 UTC, Linary requested changes

2021-05-20 11:36 UTC, Linary commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +                (this.lastNames != names && !Arrays.equals(this.lastNames, names))) {
向左缩进4个字符

2021-05-20 11:37 UTC, imbajin commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +                (this.lastNames != names && !Arrays.equals(this.lastNames, names))) {
the memory address of `String` can't be same & align with `(`

2021-05-20 12:28 UTC, DoubleBabylol commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +                (this.lastNames != names && !Arrays.equals(this.lastNames, names))) {
done

2021-05-20 13:11 UTC, imbajin commented on src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
> +            (this.lastNames != names &&
no need to compare address because `Arrays.equals()` will compare them first

2021-05-21 06:08 UTC, Linary approved these changes

2021-05-21 06:09 UTC, merged